name: regenie
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.12.2
  - ipykernel=6.29.2
  - pandas=2.2.0
  - openpyxl=3.1.2
  - numpy=1.26.4
  - scipy=1.12.0
  - bioconda::regenie=3.4.1
  # R
  - r-base=4.2.3
  - r-irkernel=1.3.2
  - r-devtools=2.4.5
  - r-tidyverse=2.0.0
  - r-argparser=0.7.1
  #- r-plotly=4.10.2
  #- r-cowplot=1.1.1
  #- r-qqman=0.1.9
  # For EXCEED API
  - r-checkmate=2.3.0
  - r-redcapr=1.1.0
